var tiktok_stim = [
  {
    "category_code_alphabetical": "R",
    "category_code_numerical": 18,
    "video_name_count": "ai_recreation_1",
    "category": "ai_recreation",
    "tiktok_search_prompt": "asking ai to show me ancient civilization",
    "link": "https://www.tiktok.com/@ancientvisionsai/video/7440205130512846113?q=asking%20ai%20to%20show%20me%20empire&t=1757262955788",
    "MediaInfo_video_length_seconds": 18.598,
    "MediaInfo_video_length_milliseconds": 18598,
    "channel": "ancientvisionsai",
    "video_name_count_channel": "ai_recreation_1_ancientvisionsai",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/first_demo_stim/ai_recreation_1_ancientvisionsai.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "S",
    "category_code_numerical": 19,
    "video_name_count": "plants_1",
    "category": "plants",
    "tiktok_search_prompt": "houseplant tour",
    "link": "https://www.tiktok.com/@thehappysprig/video/7521782021924867383?q=houseplant%20tour&t=1754690642602",
    "MediaInfo_video_length_seconds": 20.131,
    "MediaInfo_video_length_milliseconds": 20131,
    "channel": "thehappysprig",
    "video_name_count_channel": "plants_1_thehappysprig",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/first_demo_stim/plants_1_thehappysprig.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "T",
    "category_code_numerical": 20,
    "video_name_count": "forging_1",
    "category": "forging",
    "tiktok_search_prompt": "hand forging",
    "link": "https://www.tiktok.com/@blacksmithingmaster/video/7501143969456295210",
    "MediaInfo_video_length_seconds": 13.885,
    "MediaInfo_video_length_milliseconds": 13885,
    "channel": "blacksmithingmaster",
    "video_name_count_channel": "forging_1_blacksmithingmaster",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/first_demo_stim/forging_1_blacksmithingmaster.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "U",
    "category_code_numerical": 21,
    "video_name_count": "ootd_1",
    "category": "ootd",
    "tiktok_search_prompt": "outfit of the day",
    "link": "https://www.tiktok.com/@lynnwisseh_/video/7513320230412651806?q=outfit%20of%20the%20day&t=1753029671133",
    "MediaInfo_video_length_seconds": 14.471,
    "MediaInfo_video_length_milliseconds": 14471,
    "channel": "lynnwisseh_",
    "video_name_count_channel": "ootd_1_lynnwisseh_",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/first_demo_stim/ootd_1_lynnwisseh_.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "V",
    "category_code_numerical": 22,
    "video_name_count": "trapeze_1",
    "category": "trapeze",
    "tiktok_search_prompt": "aerial trapeze",
    "link": "https://www.tiktok.com/@hopechulka/video/7564210155496213815?q=aerial%20trapeze&t=1762124551264",
    "MediaInfo_video_length_seconds": 15.7,
    "MediaInfo_video_length_milliseconds": 15700,
    "channel": "hopechulka",
    "video_name_count_channel": "trapeze_1_hopechulka",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/first_demo_stim/trapeze_1_hopechulka.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "W",
    "category_code_numerical": 23,
    "video_name_count": "squegee_1",
    "category": "squeegee",
    "tiktok_search_prompt": "window squeegee",
    "link": "https://www.tiktok.com/@zaynethewindowguy/video/7506915668898467114?q=window%20squeegee&t=1762128880567",
    "MediaInfo_video_length_seconds": 23.265,
    "MediaInfo_video_length_milliseconds": 23265,
    "channel": "zaynethewindowguy",
    "video_name_count_channel": "squeegee_1_zaynethewindowguy",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/first_demo_stim/squeegee_1_zaynethewindowguy.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "X",
    "category_code_numerical": 24,
    "video_name_count": "hydrodip_1",
    "category": "hydrodip",
    "tiktok_search_prompt": "hydropdipping tumbler",
    "link": "https://www.tiktok.com/@sbub20/video/6907661047742614790?q=hydro%20dipping%20tumbler&t=1754761178749",
    "MediaInfo_video_length_seconds": 11.864,
    "MediaInfo_video_length_milliseconds": 11864,
    "channel": "sbub20",
    "video_name_count_channel": "hydrodip_1_sbub20",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/hydrodip/hydrodip_1_sbub20.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "X",
    "category_code_numerical": 24,
    "video_name_count": "hydrodip_2",
    "category": "hydrodip",
    "tiktok_search_prompt": "hydropdipping tumbler",
    "link": "https://www.tiktok.com/@perfectharmonydesign/video/6879493120099126533?q=hydro%20dipping%20tumbler&t=1754761178749",
    "MediaInfo_video_length_seconds": 15.812,
    "MediaInfo_video_length_milliseconds": 15812,
    "channel": "perfectharmonydesign",
    "video_name_count_channel": "hydrodip_2_perfectharmonydesign",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/hydrodip/hydrodip_2_perfectharmonydesign.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "X",
    "category_code_numerical": 24,
    "video_name_count": "hydrodip_3",
    "category": "hydrodip",
    "tiktok_search_prompt": "hydropdipping tumbler",
    "link": "https://www.tiktok.com/@melissastumblers/video/6989004719125482758?q=hydrodip%20tumbler&t=1754761351959",
    "MediaInfo_video_length_seconds": 24.31,
    "MediaInfo_video_length_milliseconds": 24310,
    "channel": "melissastumblers",
    "video_name_count_channel": "hydrodip_3_melissastumblers",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/hydrodip/hydrodip_3_melissastumblers.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "X",
    "category_code_numerical": 24,
    "video_name_count": "hydrodip_4",
    "category": "hydrodip",
    "tiktok_search_prompt": "hydropdipping tumbler",
    "link": "https://www.tiktok.com/@afterlife_industries/video/7361862463706664238?q=hydrodip%20tumbler&t=1754761351959",
    "MediaInfo_video_length_seconds": 28.821,
    "MediaInfo_video_length_milliseconds": 28821,
    "channel": "afterlife_industries",
    "video_name_count_channel": "hydrodip_4_afterlife_industries",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/hydrodip/hydrodip_4_afterlife_industries.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "X",
    "category_code_numerical": 24,
    "video_name_count": "hydrodip_5",
    "category": "hydrodip",
    "tiktok_search_prompt": "hydropdipping tumbler",
    "link": "https://www.tiktok.com/@bekindbecustom/video/7055871187049762095?q=bekind%20tumbler%20hydrodip&t=1754775406681",
    "MediaInfo_video_length_seconds": 15.87,
    "MediaInfo_video_length_milliseconds": 15870,
    "channel": "bekindbecustom",
    "video_name_count_channel": "hydrodip_5_bekindbecustom",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/hydrodip/hydrodip_5_bekindbecustom.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "X",
    "category_code_numerical": 24,
    "video_name_count": "hydrodip_6",
    "category": "hydrodip",
    "tiktok_search_prompt": "hydropdipping tumbler",
    "link": "https://www.tiktok.com/@annaliamandco/video/6885365081404673285?q=hydro%20dipping%20flask&t=1754764303788",
    "MediaInfo_video_length_seconds": 21.812,
    "MediaInfo_video_length_milliseconds": 21812,
    "channel": "annaliamandco",
    "video_name_count_channel": "hydrodip_6_annaliamandco",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/hydrodip/hydrodip_6_annaliamandco.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "Y",
    "category_code_numerical": 25,
    "video_name_count": "cars_1",
    "category": "cars",
    "tiktok_search_prompt": "aston martin",
    "link": "https://www.tiktok.com/@officialnovitec/video/7407701771545513248",
    "MediaInfo_video_length_seconds": 13.745,
    "MediaInfo_video_length_milliseconds": 13745,
    "channel": "officialnovitec",
    "video_name_count_channel": "cars_1_officialnovitec",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/cars/cars_1_officialnovitec.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "Y",
    "category_code_numerical": 25,
    "video_name_count": "cars_2",
    "category": "cars",
    "tiktok_search_prompt": "lamborghini",
    "link": "https://www.tiktok.com/@luxury.speed/video/7475003858863885599?q=lamborghini%20car&t=1754688333790",
    "MediaInfo_video_length_seconds": 15.347,
    "MediaInfo_video_length_milliseconds": 15347,
    "channel": "luxury.speed",
    "video_name_count_channel": "cars_2_luxury.speed",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/cars/cars_2_luxury.speed.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "Y",
    "category_code_numerical": 25,
    "video_name_count": "cars_3",
    "category": "cars",
    "tiktok_search_prompt": "ferrari",
    "link": "https://www.tiktok.com/@creativebespoke/video/7535916459311009054?q=mclaren%20car&t=1754688395452",
    "MediaInfo_video_length_seconds": 18.389,
    "MediaInfo_video_length_milliseconds": 18389,
    "channel": "creativebespoke",
    "video_name_count_channel": "cars_3_creativebespoke",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/cars/cars_3_creativebespoke.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "Y",
    "category_code_numerical": 25,
    "video_name_count": "cars_4",
    "category": "cars",
    "tiktok_search_prompt": "mclaren",
    "link": "https://www.tiktok.com/@supercarsworldwide_/video/7501940847328431403?q=bugatti%20car&t=1754688419684",
    "MediaInfo_video_length_seconds": 12.631,
    "MediaInfo_video_length_milliseconds": 12631,
    "channel": "supercarsworldwide_",
    "video_name_count_channel": "cars_4_supercarsworldwide_",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/cars/cars_4_supercarsworldwide_.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "Y",
    "category_code_numerical": 25,
    "video_name_count": "cars_5",
    "category": "cars",
    "tiktok_search_prompt": "bugatti",
    "link": "https://www.tiktok.com/@luke78491/video/7329287747833826592?q=green%20sports%20car&t=1754789515174",
    "MediaInfo_video_length_seconds": 12.631,
    "MediaInfo_video_length_milliseconds": 12631,
    "channel": "luke78491",
    "video_name_count_channel": "cars_5_luke78491",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/cars/cars_5_luke78491.mp4",
    "length_grouping": "demo"
  },
  {
    "category_code_alphabetical": "Y",
    "category_code_numerical": 25,
    "video_name_count": "cars_6",
    "category": "cars",
    "tiktok_search_prompt": "candy red sports car",
    "link": "https://www.tiktok.com/@thecarforum/video/7537151118573358350?q=lime%20green%20ferrari&t=1755188043366",
    "MediaInfo_video_length_seconds": 17.251,
    "MediaInfo_video_length_milliseconds": 17251,
    "channel": "thecarforum",
    "video_name_count_channel": "cars_6_thecarforum",
    "video_pathway": "stimuli/tiktok_stim_veryfast_social/demos/cars/cars_6_thecarforum.mp4",
    "length_grouping": "demo"
  }
]